CREATE OR REPLACE TYPE str_obj_nm_tt AS TABLE OF VARCHAR2(30)
/

CREATE OR REPLACE TYPE str_sm_tt AS TABLE OF VARCHAR2(255)
/

CREATE OR REPLACE TYPE str_maxcol_tt AS TABLE OF VARCHAR2(4000)
/

CREATE OR REPLACE TYPE str_maxvc2_tt AS TABLE OF VARCHAR2(32767)
/

CREATE OR REPLACE TYPE num_tt AS TABLE OF NUMBER
/

CREATE OR REPLACE TYPE dt_tt AS TABLE OF DATE
/

CREATE SYNONYM str_tt FOR str_maxcol_tt;
